//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Details
    {
        public int ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Code { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
        public string Length { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<bool> Offer_Chk { get; set; }
        public Nullable<decimal> Offer_Percentage { get; set; }
        public Nullable<decimal> Offer_Price { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
