//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Details = new HashSet<Product_Details>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PC_ID { get; set; }
        public Nullable<int> SPC_ID { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public string Production_Country { get; set; }
        public string Material { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Details> Product_Details { get; set; }
    }
}
