//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public decimal Offer_Price { get; set; }
        public Nullable<decimal> Offer_Percentage { get; set; }
        public string Offer_Until_Date { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public byte[] Image { get; set; }
    }
}
